FROM node:20-alpine as build

WORKDIR /app

COPY server/package*.json ./

RUN npm install

COPY server/ ./

RUN npm run build

# Production stage
FROM node:20-alpine

WORKDIR /app

COPY --from=build /app/dist ./dist
COPY --from=build /app/package*.json ./
COPY --from=build /app/prisma ./prisma

RUN npm install --production

EXPOSE 5000

CMD ["npm", "start"]