name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push client
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile.client
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-client:latest
      
      - name: Build and push server
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile.server
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-server:latest